#ifndef CONSTANTS_H
#define CONSTANTS_H

#define INITIAL_FLOOR_COUNT 100
#define FLOOR_WIDTH 50
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define LOGS_ON 1

#define GRAVITY 98.0f
#define FLOOR_HEIGHT 10.0f
#define PLAYER_WIDTH 32.0f
#define PLAYER_HEIGHT 32.0f
#define MAX_FLOOR_WIDTH 200
#define MIN_FLOOR_WIDTH 50
#define MAX_FLOOR_SPEED 10.0f
#define MULTIPLIER 25.0f
#define PLAYER_ACCELERATION 2000.0f
#define PLAYER_DECELERATION 800.0f
#define PLAYER_MAX_VELOCITY 500.0f
#define PLAYER_MAX_MOMENTUM 600.0f
#define JUMP_VELOCITY_BASE -300.0f
#define JUMP_VELOCITY_BOOST_MULTIPLIER 0.1f

#endif